on:
  push:
    branches: main
  pull_request: # to remove before pushing to main
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: spotifind-ecr

jobs:
  docker-build-and-push:
    name: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::879381276911:role/ecr-image-deploy-role
          role-session-name: DeployToECR
          aws-region: ap-southeast-1
      
      - name: Verify Auth
        run: aws sts get-caller-identity
